# Generated by Django 4.2.7 on 2023-11-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='blood_type',
            field=models.CharField(choices=[('O', 'O'), ('A', 'A'), ('B', 'B'), ('AB', 'AB')], default='O', max_length=2),
        ),
        migrations.AddField(
            model_name='person',
            name='favorite_artist',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Prefer Not To Say')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='person',
            name='iq',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='person',
            name='mbti',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='myapp/images'),
        ),
        migrations.AddField(
            model_name='person',
            name='zodiac_sign',
            field=models.CharField(blank=True, choices=[('CORN', 'Capricorn'), ('AQUA', 'Aquarius'), ('PISC', 'Pisces'), ('ARIES', 'Aries'), ('TAU', 'Taurus'), ('GEM', 'Gemini'), ('CANC', 'Cancer'), ('LEO', 'Leo'), ('VIRG', 'Virgo'), ('LIBR', 'Libra'), ('SCOR', 'Scorpio'), ('SAG', 'Sagittarius')], max_length=5, null=True),
        ),
    ]
